{% set name = "pulumi-sdks" %}
{% set version = "3.118.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pulumi/pulumi/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5ce1353b814e3a755093d9c0cedc70128801ccf090d36cc9dcead34e32244b9f

build:
  number: 0
  skip: true  # [not linux]

outputs:
  - name: pulumi-core
    script: build_pulumi_core.sh
    requirements:
      build:
        - {{ compiler('go') }}
        - make
        - go-licenses
      run:
        - {{ pin_subpackage("pulumi-core") }}
    test:
      commands:
        - pulumi version

  - name: pulumi-sdk-go
    script: build_pulumi_go.sh
    requirements:
      build:
        - {{ compiler('go') }}
        - make
        - go-licenses
      run:
        - {{ pin_subpackage("pulumi-core") }}
    test:
      commands:
        - test -f $PREFIX/bin/pulumi-language-go

  - name: pulumi-sdk-python
    script: build_pulumi_python.sh
    requirements:
      build:
        - {{ compiler('go') }}
        - make
        - go-licenses
      run:
        - {{ pin_subpackage("pulumi-core") }}
        - python
    test:
      commands:
        - test -f $PREFIX/bin/pulumi-analyzer-policy-python
        - test -f $PREFIX/bin/pulumi-language-python
        - test -f $PREFIX/bin/pulumi-language-python-exec
        - test -f $PREFIX/bin/pulumi-resource-pulumi-python

  # The nodejs sdk needs more work; let's leave it for the feedstock
  # - name: pulumi-sdk-nodejs
  #   script: build_pulumi_nodejs.sh
  #   requirements:
  #     build:
  #       - {{ compiler('go') }}
  #       - make
  #       - go-licenses
  #       - yarn
  #     run:
  #       - {{ pin_subpackage("pulumi-core") }}
  #   test:
  #     commands:
  #       - pulumi new nodejs

about:
  home: https://www.pulumi.com/
  summary: Infrastructure as Code in any Programming Language
  description: |
    Pulumi is an infrastructure as code platform that allows you to use familiar
    programming languages and tools to build, deploy, and manage cloud infrastructure.
    Pulumi is free, open source, and optionally pairs with the Pulumi Cloud to
    make managing infrastructure secure, reliable, and hassle-free.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  doc_url: https://www.pulumi.com/docs/
  dev_url: https://github.com/pulumi/pulumi

extra:
  recipe-maintainers:
    - zklaus
